service: logging

provider:
  name: openwhisk

custom:
  config: ${file(config.json)}

functions:
  logstash-forwarder:
    handler: dist/index.main
    parameters:
      actions: ${self:custom.config.actions}
      from: ${self:custom.config.from}
      logstash: ${self:custom.config.logstash}
      events:
        - schedule: cron(* * * * *)

plugins:
  - serverless-openwhisk
